[package]
name = "counter"
version = "0.0.1"

[dependencies]
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }

[addresses]
rooch_examples =  "0xc884e7019d1f68755ea944efbae61f2292b25c4257ef90bbea61ec1ac4b45e36"
moveos_std =  "0x2"
rooch_framework =  "0x3"

[dev-addresses]
rooch_examples = "0x42"